language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists dbhellobooks_test;' -U postgres
  - psql -c 'create database dbhellobooks_test;' -U postgres
  - psql -c "create user usrhello with login password 'HelloBooksPassword$';" -U postgres
  - sequelize db:migrate:undo:all
  - sequelize db:migrate

env:
  - NODE_ENV=test

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
