version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-books
permissions:
  - object: /home/ec2-user/hello-books
    pattern: "**"
    owner: ec2-user
    mode: 700
    type:
      - file
  - object: /home/ec2-user/hello-books
    owner: ec2-user
    mode: 777
    type:
      - directory
  - object: /home/ec2-user
    pattern: "*hello-books*"
    owner: ec2-user
    mode: 777
    type:
      - directory
hooks:
  BeforeInstall:
    - location: aws-deploy/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: aws-deploy/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws-deploy/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: aws-deploy/stop_server.sh
      timeout: 300
      runas: ec2-user
